bash: Standadrise output()
Signed-off-by: Mark Grant <m.grant.prg@gmail.com>

diff --git a/src/prg/bash/agmaint.sh.in b/src/prg/bash/agmaint.sh.in
--- a/src/prg/bash/agmaint.sh.in
+++ b/src/prg/bash/agmaint.sh.in
@@ -79,13 +79,17 @@ Usage is $0 [OPTIONS]
 EOF
 }
 
-# Output $1 to stdout or stderr depending on $2.
+# Standard function to emit messages depending on various parameters.
+# Parameters -	$1 What:-	The message to emit.
+#		$2 Where:-	stdout == 0
+#				stderr == 1
+# No return value.
 output()
 {
-	if [ $2 = 0 ]; then
-		echo "$outputprefix$1"
+	if (( !$2 )); then
+		printf "%s\n" "$1"
 	else
-		echo "$outputprefix$1" 1>&2
+		printf "%s\n" "$1" 1>&2
 	fi
 }
 
